JDP200801-29 Group Entity bug fix
piotr-grosicki/project-jdp-2008-01 pull request #10
Opened 2020-08-24 10:30 UTC by Greem666

Changed Group Entity's class name from "Group" to "GroupEntity", @Table name to "PRODUCT_GROUPS", and modified group class-related entries in Product class.

2020-08-25 07:48 UTC, piotr-grosicki requested changes

2020-08-25 07:48 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/group/GroupEntity.java
> +public class GroupEntity {
klasa encji powinna sie nazywac `Group`

2020-08-25 07:48 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/group/GroupEntity.java
> +@Table(name="PRODUCT_GROUPS")
wystarczy `groups`

2020-08-25 07:48 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/group/dao/GroupEntityDao.java
> +public interface GroupEntityDao extends CrudRepository<GroupEntity, Long> {
`GroupDao`

2020-08-25 11:58 UTC, piotr-grosicki requested changes
konflikty

2020-08-25 15:01 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/group/GroupEntity.java
> +public class GroupEntity {
W najnowszym commit zmienilem nazwe encji na Group.

2020-08-25 15:01 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/group/GroupEntity.java
> +@Table(name="PRODUCT_GROUPS")
W najnowszym commit zmienilem nazwe tabeli na GROUPS.

2020-08-25 15:02 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/group/dao/GroupEntityDao.java
> +public interface GroupEntityDao extends CrudRepository<GroupEntity, Long> {
W najnowszym commit, po zmianie nazwy encji, poprawilem tez nazwy Dao.

2020-08-25 15:04 UTC, Greem666 commented
Najnowszy commit z wymaganymi zmianami nazwy encji, uwzglednai takze update z master branch'a, poniewaz struktura projektu sie zmienila po spotkaniu 25.08.2020.

2020-08-26 07:37 UTC, piotr-grosicki approved these changes

2020-08-26 07:37 UTC, merged