JDP200801-17
piotr-grosicki/project-jdp-2008-01 pull request #14
Opened 2020-08-24 14:58 UTC by Greem666

Includes changes introduced in JDP200801-28, and indirectly JDP200801-29 (due to problems with Group Entity implementation). Also required slight alterations due to conflicts with Cart-User relationship, which was implemented after branch -17 was created.

2020-08-25 07:55 UTC, piotr-grosicki requested changes

2020-08-25 07:55 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/group/GroupEntity.java
> +public class GroupEntity {
to zadanie nie powinno zawierac zmian w tym pliku

2020-08-25 11:58 UTC, piotr-grosicki requested changes
konflikty

2020-08-26 07:42 UTC, piotr-grosicki requested changes
konflikt ;)

2020-08-26 16:08 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/group/GroupEntity.java
> +public class GroupEntity {
Poprawione, zmiany przeniesiono do JDP200801-29.

2020-08-26 16:10 UTC, Greem666 commented
> konflikt ;)

Poprawione po pull`u z mastera.

2020-08-26 16:11 UTC, Greem666 commented
> > konflikt ;)
> 
> Poprawione po pull`u z mastera.

2020-08-27 07:08 UTC, piotr-grosicki approved these changes

2020-08-27 07:08 UTC, merged