Jdp200801 19 - CartTestSuite
piotr-grosicki/project-jdp-2008-01 pull request #15
Opened 2020-08-24 19:20 UTC by zagPatryk

CartTestSuite

2020-08-25 07:58 UTC, piotr-grosicki requested changes

2020-08-25 07:58 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/group/Group.java
> +@Entity(name="Groupzzzzzzzzz")
nie wypuszczamy na branch nie ukonczonego kodu bo zrobi sie smietnik z gita

2020-08-25 11:58 UTC, piotr-grosicki requested changes
konflikty

2020-08-26 07:42 UTC, piotr-grosicki requested changes
konflikt ;)

2020-08-26 19:02 UTC, zagPatryk commented
Konflikt naprawiony. Dodatkowo musiałem wprowadzić zmiane w encji cart. Dodałem taska JDP200801-30 - brakujące cascade/fetch.

2020-08-27 07:10 UTC, piotr-grosicki requested changes

2020-08-27 07:10 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/cart/CartTestSuite.java
> +    public void saveCart() {
brakuje testow innych literek `CRUD` ;) tutaj mamy tylko `C - create`

2020-08-27 07:12 UTC, piotr-grosicki commented
testy nei przechodza

2020-08-27 20:10 UTC, closed without merging