Jdp200801 16
piotr-grosicki/project-jdp-2008-01 pull request #22
Opened 2020-08-27 13:02 UTC by MsFaxe

2020-08-27 14:18 UTC, Greem666 reviewed
Adnotacja @transactional sprawia, że całość instrukcji w każdym z testów w tym TestSuite wykona się na jednym commit'cie. Sprawia to, że nie zauważysz problemów w komunikacji z bazą danych, ponieważ wszystkie instrukcje przed końcem testów Hibernate wykona przede wszystkim na swoich Bean`ach. Moja sugestia: wyłącz @transactional, i spróbuj odpalić testy jeszcze raz, z wyłączoną bazą danych H2. Możliwe, że wydobędziesz dzięki temu więcej info nt. tego, czy encje dobrze śmigają.
Upewnij się, że linkujesz w kodzie każdą encję z każdą, i je w odpowiedniej kolejności zapisujesz - inaczej bez @transactional zaczną rzucać błędami na lewo i prawo.

2020-08-27 14:18 UTC, Greem666 commented on src/test/java/com/kodilla/ecommercee/domain/order/OrderTestSuit.java
> +@Transactional
Adnotacja @Transactional sprawia, że całość instrukcji w każdym z testów w tym TestSuite wykona się na jednym commit'cie. Sprawia to, że nie zauważysz problemów w komunikacji z bazą danych, ponieważ wszystkie instrukcje przed końcem testów Hibernate wykona przede wszystkim na swoich Bean`ach. Moja sugestia: wyłącz @Transactional, i spróbuj odpalić testy jeszcze raz, z wyłączoną bazą danych H2. Możliwe, że wydobędziesz dzięki temu więcej info nt. tego, czy encje dobrze śmigają.
Upewnij się, że linkujesz w kodzie każdą encję z każdą, i je w odpowiedniej kolejności zapisujesz - inaczej bez @Transactional zaczną rzucać błędami na lewo i prawo.

2020-08-27 14:44 UTC, MsFaxe commented on src/test/java/com/kodilla/ecommercee/domain/order/OrderTestSuit.java
> +@Transactional
Upewnij się, że linkujesz w kodzie każdą encję z każdą i je w odpowiedniej kolejności zapisujesz - a czy @Transactional, nie jest własnie po to, żeby nie zastanawiać się, czy zapisuję to w dobrej kolejności i czy łączę, bo robi to za mnie spring?

2020-08-27 15:24 UTC, Greem666 commented on src/test/java/com/kodilla/ecommercee/domain/order/OrderTestSuit.java
> +@Transactional
@Transactional pomaga, ale ja się w swoich testach encji Product natknąłem na sytuację, gdy usunięcie produktu zlinkowanego z encją Group nie było zapisywane w bazie danych, i asercje po tych czynnościach zwracały cały czas ten sam produkt z bazy danych w relacji do Group, który w teorii usunąłem parę linijek wcześniej. Wszystko dlatego, że commit następował po wywołaniu zlinkowanych produktów do grupy, podczas asercji grupy - parę linijek kodu poniżej usuwania produktu.

2020-08-30 20:29 UTC, zagPatryk approved these changes
Approved. Można połączyć po dodaniu do mastera JDP200801-33

2020-08-31 07:45 UTC, piotr-grosicki requested changes

2020-08-31 07:45 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/order/OrderTestSuit.java
> +    public void testDeleteOrderWithoutDeleteComponents() {
ten test powinien sprawdzac czy nie zostana usuniete produkty a nie cart, zmienialismy ostatnio zeby order nie zawieral cart wiec nie ma mozliwosci zeby sie usunal ;)

2020-08-31 10:54 UTC, MsFaxe commented on src/test/java/com/kodilla/ecommercee/domain/order/OrderTestSuit.java
> +    public void testDeleteOrderWithoutDeleteComponents() {
Zmiany wprowadzone. Faktycznie w tym teście przeoczyłam, że należy sprawdzać Product, a nie Cart

2020-09-05 11:05 UTC, Greem666 approved these changes
Wszystko wyglada ok, testy przechodza lokalnie, i ogolnie jest spoko :)

2020-09-05 14:43 UTC, piotr-grosicki approved these changes

2020-09-05 14:43 UTC, merged