User inital endpoints implementation
piotr-grosicki/project-jdp-2008-01 pull request #28
Opened 2020-08-29 18:48 UTC by krysiakpawel

2020-08-29 22:02 UTC, zagPatryk requested changes
createUser, blockUser działają ale getUserKey wyrzuca null pointer exception

2020-08-29 22:02 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        long userkey = userDto.getUserkey();
Przez te linie wywala null pointer exception. Próbujesz pobrać z userDto wartość userKey'a ale nie jest on nadany

2020-08-30 21:31 UTC, zagPatryk approved these changes
Trochę okroiłeś userDto ale na wczesną implementację jest dobrze. Wszystkie endpointy 'odpowiadają'.
![1](https://user-images.githubusercontent.com/62852383/91669894-e449b680-eb18-11ea-8e02-f5b08c0ddbde.png)
![2](https://user-images.githubusercontent.com/62852383/91669895-e4e24d00-eb18-11ea-84a3-06f793295bec.png)
![3](https://user-images.githubusercontent.com/62852383/91669897-e57ae380-eb18-11ea-8037-c3f99377bf49.png)

2020-08-31 07:47 UTC, piotr-grosicki approved these changes

2020-08-31 07:47 UTC, merged