UserDaoTestSuite
piotr-grosicki/project-jdp-2008-01 pull request #31
Opened 2020-08-31 23:38 UTC by MarcinSkrzecz

2020-09-04 11:05 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/order/Order.java
>      public Order(User user, Cart cart) {
Brak dowiazania Order'a to User'a w konstruktorze.

2020-09-04 11:06 UTC, Greem666 commented on src/test/java/com/kodilla/ecommercee/domain/user/dao/UserDaoTestSuite.java
> +    }
Te dwa testy w sumie osiagaja to samo, i mozna je polaczyc w jeden test testUserReadWrite.
Dodatkowo, te dodatki "_OK" po tescie w sumie nie rozumiem po co zostaly dodane.

2020-09-04 11:06 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/order/Order.java
>          this.user = user;
Brak dowiazania Order'a to User'a w konstruktorze.

2020-09-04 11:08 UTC, Greem666 commented on src/test/java/com/kodilla/ecommercee/domain/user/dao/UserDaoTestSuite.java
> +        Assert.assertEquals(user.getId(), userAfterUpdate.getId(), 0);
Encja User ma w sobie zaszyta adnotacje @EqualsAndHashCode.Include nad polem "id". Oznacza to, ze mozesz przyrownywac egzemplarze tej encji wprost do siebie, i beda porownywane na podstawie tylko ich pola id - nie musisz go z nich manualnie wyciagac.

2020-09-04 11:09 UTC, Greem666 requested changes
Zerknij na moje komentarze i je wprowadz.

2020-09-04 16:18 UTC, Greem666 approved these changes

2020-09-05 14:44 UTC, piotr-grosicki commented
konflikt w Order

2020-09-05 14:44 UTC, piotr-grosicki requested changes
konflikt w Order

2020-09-06 10:16 UTC, piotr-grosicki approved these changes

2020-09-06 10:16 UTC, merged