JDP200801-24 Real implementation of OrderController
piotr-grosicki/project-jdp-2008-01 pull request #34
Opened 2020-09-01 15:44 UTC by Greem666

- Added implementation of OrderMapper, ProductMapper (needed in OrderMapper's operation) & OrderService
- Added convenience classes for <EntityName>NotFoundExeption, inheriting unchecked functionality from RuntimeException
- Various fixes to naming in Entities (productList -> products etc., to improve Lombok-generated getters readability etc.)

2020-09-02 18:10 UTC, MsFaxe requested changes
Po ostatni mergu masz dwa konflikty

Wydaje mi się, że zmiany wprowadzone przez Ciebie w klasach dotyczących carta, usera, group i product nie mogą się znajdować na jednym branchu, bo wprowadzi to nie tylko zamieszanie w odnalezieniu później zmian, ale nad częścią z tych klas obecnie pracują inni, co może znacznie wpłynąć na zaburzenie koncepcji jakie ma każdy przy własnej implementacji

2020-09-03 14:07 UTC, Greem666 commented
> Po ostatni mergu masz dwa konflikty
> 
> Wydaje mi się, że zmiany wprowadzone przez Ciebie w klasach dotyczących carta, usera, group i product nie mogą się znajdować na jednym branchu, bo wprowadzi to nie tylko zamieszanie w odnalezieniu później zmian, ale nad częścią z tych klas obecnie pracują inni, co może znacznie wpłynąć na zaburzenie koncepcji jakie ma każdy przy własnej implementacji

Ok, trochę dużo było by z tym zachodu, żeby wszystko odplątać plik po pliku, więc po prostu zresetowałem swoją gałąź JDP200801-24 do samego początku od którego startowała, i zrobiłem od nowa implementację, starając się nie ruszać innych encji. Pozbyłem się też zwracania wyjątków. Zmieniłem też filozofię tego jak się kreuje zamówienia, wychodząc z założenia, że są one kreowane z tego, co jest aktualnie w koszyku, który jest zapisany w bazie danych, więc nowe zamówienie może powstać tylko wtedy, gdy poda się ID istniejącego w DB koszyka, który ma w sobie jakieś produkty. Nie implementowałem opróżniania koszyka po stworzeniu zamówienia, ponieważ wydaje mi się, że powinien to robić kontroller encji Cart, po stworzeniu zamówienia (ma do tego w specyfikacji wyszczególnioną funkcję). 
Chyba wyszło całkiem nieźle - daj znać czy teraz wszystko jest ok.

2020-09-05 10:33 UTC, MsFaxe approved these changes
wszystkie testy w postmanie przechodzą :) 
projekt się buduje, nie ma konfliktów, jest super :D

2020-09-05 14:44 UTC, piotr-grosicki requested changes
Konflikt w Order

2020-09-05 16:22 UTC, Greem666 commented
Zrobilem update z master'a, rozwiazalem konflikty w klasie Order i naprawilem wynikajace z nich problemy z testami w OrderTestSuite.

2020-09-06 10:21 UTC, piotr-grosicki requested changes

2020-09-06 10:21 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/controller/OrderControllerTestSuite.java
> +public class OrderControllerTestSuite {
nie zostawiamy niepotrzebnych klas w kodzie, zakomentowany kod zawsze powinien byc usuwany

2020-09-06 10:21 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/product/ProductDtoStub.java
> +public class ProductDtoStub {
czemu stub?

2020-09-06 10:21 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +            orderForUpdate.setUser(user);
nie ustalilismy na callu, ze zmiana usera nie ma sensu?

2020-09-06 10:52 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/domain/product/ProductDtoStub.java
> +public class ProductDtoStub {
To jest pozostalosc po mojej implementacji, ktora byla pierwotnie robiona przed pelna implementacja kontrollera dla encji Product. Zostawilem to w kodzie, poniewaz ProductController na wstepnej implementacji uzywal tego Dto z jednym polem w klasie do swoich celow, a nie chcialem w tym commit wrzucac poprawek do pobocznych klas bez potrzeby. Teraz chyba po wczorajszych merge'ach i realnej implemntacji ProductController, ta klasa nie spelnia zadnej istotnej funkcji, wiec moge ja usunac.

2020-09-06 10:55 UTC, Greem666 commented on src/test/java/com/kodilla/ecommercee/controller/OrderControllerTestSuite.java
> +public class OrderControllerTestSuite {
Ta klasa byla mi tylko potrzebna do testow OrderController, i zostawilem ja, zeby moi recenzenci tez mogli sobie cos wrzucic w baze danych, zeby testy w Postmanie przeszly. Teraz tez moze byc jeszcze przydatna, poniewaz nadal nie mamy implementacji kontrolerow dla User i Cart w kodzie (wiec nie mozemy zadnych rekordow tych encji przez Postmana), ale w sumie moge to juz usunac, skoro Joanna juz sprawdzila poprawnosc dzialania OrderController po swojej stronie.

2020-09-06 11:05 UTC, Greem666 commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +            orderForUpdate.setUser(user);
100% racja, umknelo mi to przy refactoringu juz istniejacego kodu - poprawione.

2020-09-07 13:07 UTC, piotr-grosicki approved these changes

2020-09-07 13:07 UTC, merged