User controller final method implementation
piotr-grosicki/project-jdp-2008-01 pull request #43
Opened 2020-09-10 21:04 UTC by krysiakpawel

2020-09-11 07:35 UTC, piotr-grosicki requested changes

2020-09-11 07:35 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        user.setStatus(newUserStatus);
ten kod powinien znajdowac sie w serwisie, controller nie powinien wiedziec jak zablokowac usera

2020-09-11 07:35 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        Long generatedUserKey = userService.createUserKey();
ten kod powinien znajdowac sie w serwisie, controller nie powinien wiedziec jak wygenerowac klucz

2020-09-11 07:35 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +            if(currentTimeSecs - user.getUserKey() < 30){   //UserKey is active for 30 seconds for Postman tests purpose - for one hour change 30 -> 3600
ten kod powinien znajdowac sie w serwisie, controller nie powinien wiedziec jak sprawdzic status klucza

2020-09-11 07:35 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +        if(user.isPresent()) {
czemu wyjmujesz go z optionala jesli wiesz, ze moze byc null? dane z optionala powinny byc wyciagane w sposob jawny gdy sa potrzebne a nie tak jak tutaj ukryte przed potencjalnym uzytkownikiem serwisu

2020-09-11 23:27 UTC, zagPatryk requested changes
Popacz na moje komentarze i daj znać co myślisz

2020-09-11 23:27 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +            return null;
coś takiego może wysłać nulla. Umawialiśmy się że w takim wypadku zwracamy nowy obiekt new User()

2020-09-11 23:27 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        userService.getUser(userId).setStatus(newUserStatus);
lepiej by to wyglądało gdyby było pod jednym serwisem 'blockUser'. I tak w ogóle w tym wypadku to nie jest blokowanie tylko zmiana statusu. Blokowaniem by było tylko i wyłącznie gdy ustawiało by status BLOCKED tzn jakąś cyfrę za to odpowiedzialną

2020-09-11 23:27 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        userService.saveUser(userService.getUser(userId));
Jeżeli userId nie będzie istniał w bazie wyśle ci pustą wiadomosć. Umawialiśmy sie że będziemy wtedy wysytłąć pusty obiekt tzn userDto

2020-09-11 23:27 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public User getUser(@RequestParam long userId) {
W kontrolerach operujemy na obiektach Dto. Powinno zwrócić UserDto nie zwykły User

2020-09-11 23:27 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public List<User> getAllUsers(){
Do niczego nie jest używane. Na pewno jest potrzebne? Była mowa że raczej nie tworzymy nadmiarowego/niepotrzebnego kodu

2020-09-11 23:27 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public void deleteUser(final Long id){
Do niczego nie jest używane. Na pewno jest potrzebne? Była mowa że raczej nie tworzymy nadmiarowego/niepotrzebnego kodu.

2020-09-12 20:54 UTC, krysiakpawel commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public void deleteUser(final Long id){
Usunięte

2020-09-12 20:54 UTC, krysiakpawel commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public List<User> getAllUsers(){
Usunięte

2020-09-12 20:59 UTC, krysiakpawel commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public User getUser(@RequestParam long userId) {
Zmienione 👍

2020-09-12 21:06 UTC, krysiakpawel commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        userService.getUser(userId).setStatus(newUserStatus);
Przerzuciłem metodę do service. Myślę że ustawienie statusu to kwestia umowna. Tak jak mówisz - jeśli metoda ma tylko blokować - czyli zmienić na int który odpowiada statusowi zablokowany - ustawiłem wartość statusu jako zablokowany na 0, oczywiście w przypadku dalszego rozwoju można zmienić metodę na np changeStatus() i dodać kolejny @RequestParam jako newUserStatus. Zmienione według Twoich sugestii - tylko blokowanie ;)

2020-09-12 21:44 UTC, krysiakpawel commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +            return null;
Poprawione i wszystkie miejsca gdzie istnieje ryzyko zapisania Nulla również 👍

2020-09-12 21:44 UTC, krysiakpawel commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        userService.saveUser(userService.getUser(userId));
Poprawione i wszystkie miejsca gdzie istnieje ryzyko zapisania Nulla również 👍

2020-09-13 08:49 UTC, zagPatryk requested changes

2020-09-13 08:49 UTC, zagPatryk commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public UserDto getUserKey(@RequestParam Long userId) {
Skoro getUserKey to powinieneś zwracać klucz a nie użytkownika

2020-09-13 14:11 UTC, zagPatryk approved these changes
approved

2020-09-14 07:17 UTC, piotr-grosicki approved these changes

2020-09-14 07:18 UTC, merged