Jdp200801 11
piotr-grosicki/project-jdp-2008-01 pull request #8
Opened 2020-08-22 12:11 UTC by MsFaxe

2020-08-24 07:41 UTC, piotr-grosicki requested changes
konflikty :)

2020-08-24 10:58 UTC, MsFaxe commented
konflikty usunięte, projekt się buduje, chyba wszystko jest ok

2020-08-25 07:44 UTC, piotr-grosicki requested changes

2020-08-25 07:44 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/order/OrderDto.java
> +    private Cart cart;
w tym miejscu powinn byc `Dto` a nie encje

2020-08-25 07:44 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/order/OrderTestSuit.java
> +public class OrderTestSuit {
skad ten test sie tutaj wzial? :)

2020-08-25 11:57 UTC, piotr-grosicki approved these changes

2020-08-25 11:57 UTC, merged